[phases.setup]
nixPkgs = ["maven", "openjdk8"]

[phases.install]
cmds = ["mvn clean package -DskipTests"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "java -jar target/backend-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
